## Settings
title: Sam's Site
owner: Sam Brady
url: "https://akiritsu.github.io"
baseurl: "/pRoJEct-NeGYa"
permalink: /:title/
description: "I made this :3"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "sbrady_01@arcadia.edu"
github: "https://github.com/Saform"

statement: ""
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"